#服务配置
server:
  port: 7002
spring:
  application:
    name: kafka
#日志信息配置
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
#Spring Boot Actuator:监控系统配置
endpoints:
  shutdown:
    enabled: true
    path: /shutdown
    sensitive: true
management:
  security:
    enabled: false
kafka:
  broker-list: 192.168.31.157:9092,192.168.31.157:9092,192.168.31.157:9092
  producer:
    #发送失败后的重试次数，默认0
    retries: 1
    #以字节为单位控制默认的批量大小
    batch-size: 0
    #延迟时间
    linger-ms: 1
    #缓冲等待发送到服务器的记录的总内存字节数
    buffer-memory: 33554432
    #实现Serializer接口的序列化类键
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #实现Serializer接口的序列化类值
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    #消费的主题
    topic: test-topic
    #消费者组id
    gourp-id: test-group
    #是否自动提交偏移量
    enable-auto-commit: true
    #提交偏移量的间隔-毫秒
    auto-commit-ms: 1000
    #客户端消费的会话超时时间-毫秒
    session-timeout-ms: 10000
    #实现DeSerializer接口的反序列化类键
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #实现DeSerializer接口的反序列化类值
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer